### ISSUE TITLE
Routing example in tutorial gives this error: AttributeError: 'Link' object has no attribute 'add_event_handler'

### ISSUE THREAD

**Issue by Code4SAFrankie** [kkinder/puepy#8]
The example from https://docs.puepy.dev/routing.html#pages-and-routes gives the error: AttributeError: 'Link' object has no attribute 'add_event_handler'

Error: 'Link' object has no attribute 'add_event_handler'

```
Traceback (most recent call last):
  File "puepy/application.py", line 134, in mount
  File "puepy/application.py", line 174, in mount_page
  File "puepy/core.py", line 345, in mount
  File "puepy/core.py", line 167, in generate_children
  File "<stdin>", line 66, in populate
  File "puepy/core.py", line 781, in _tag
  File "puepy/core.py", line 730, in generate_tag
  File "<stdin>", line 24, in __init__
AttributeError: 'Link' object has no attribute 'add_event_handler'
```

**Comment by Code4SAFrankie** [comment]
I see the console also has the error: 

Error: QuotaExceededError: storage.sync API call exceeded its quota limitations.

**Comment by Code4SAFrankie** [comment]
The `Error: QuotaExceededError: storage.sync API call exceeded its quota limitations.` is only in Firefox, but the other error also happens in Microsoft Edge.

**Comment by Code4SAFrankie** [comment]
Here is the non-micropython error:

```
Error: 'Link' object has no attribute 'add_event_handler'

Traceback (most recent call last):

  File "/lib/python3.12/site-packages/puepy/application.py", line 134, in mount
    self.mount_page(

  File "/lib/python3.12/site-packages/puepy/application.py", line 174, in mount_page
    self.active_page.mount(selector_or_element)

  File "/lib/python3.12/site-packages/puepy/core.py", line 345, in mount
    self.generate_children()

  File "/lib/python3.12/site-packages/puepy/core.py", line 167, in generate_children
    self.populate()

  File "<exec>", line 66, in populate

  File "/lib/python3.12/site-packages/puepy/core.py", line 781, in _tag
    return self.generate_tag(name, *children, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/lib/python3.12/site-packages/puepy/core.py", line 730, in generate_tag
    element = self.components[tag_name](
              ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "<exec>", line 24, in __init__

AttributeError: 'Link' object has no attribute 'add_event_handler'. Did you mean: 'add_event_listener'?
```

**Comment by kkinder** [comment]
Good catch. Thanks for catching all these issues with the docs.

The add_event_handler vs listener was changed in a previous version, but I neglected to update docs. I'll transfer the issue to the docs repo and apply a fix. FWIW, the actual PyScript.com demo does work and is updated, so you can see it here:

https://kkinder.pyscriptapps.com/puepy-tutorial/latest/tutorial/07_routing/index.html

Do note that you can clone all of these on PyScript.com and edit them from there.

Regarding the storage issue: maybe you could use pyscript.com and provide a link to where you're seeing the issue? Experimenting at the URL above, I'm not able to reproduce it in Firefox.
